use_frameworks!

platform :ios, '9.0'

target 'Module3_Example' do
  pod 'Module3', :path => '../'

  target 'Module3_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end
